### ISSUE TITLE
mislink for t81_558_class_09_1_keras_transfer.ipynb

### ISSUE THREAD

**Issue by icefree** [jeffheaton/t81_558_deep_learning#100]
The "Open in Colab" button in **t81_558_class_09_1_keras_transfer.ipynb** links to **https://colab.research.google.com/github/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_08_5_kaggle_project.ipynb**,
should be **https://colab.research.google.com/github/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_09_1_keras_transfer.ipynb**

**Comment by jeffheaton** [comment]
Thanks, I will take a look.
