### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by MBS1984** [jeffheaton/t81_558_deep_learning#108]
Hi,

I have followed step-by-step instruction for the installation of Tensorflow using conda based on "t81_558_class_01_1_overview". However, I haven't succeeded to run the "Python Versions" script and the following error appeared:

FileNotFoundError: Could not find module 'C:\Users\-----\miniconda3\envs\tensorflow\lib\site-packages\scipy\.libs\libbanded5x.X7D476RWJKO3TRH4FXIEB4YEAKNOYBT4.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by jeffheaton** [comment]
These are usually some sort of PATH issue.  I've not run into this particular one, so there is not too much help I can give beyond suggesting to google the error and see some of the resolutions others have found.  If you Google  gfortran-win_amd64.dll python error, you will see a number of issues raised and potential resolutions.
