### ISSUE TITLE
the target encoding article url is wrong

### ISSUE THREAD

**Issue by mhamri** [jeffheaton/t81_558_deep_learning#111]
in https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_02_2_pandas_cat.ipynb

the url to the article resolve to a 404 page, here is the correct url 

correct one: 
https://maxhalford.github.io/blog/target-encoding/

wrong one:
https://maxhalford.github.io/blog/target-encoding-done-the-right-way/

**Comment by jeffheaton** [comment]
Thanks! I just updated the link.
