### ISSUE TITLE
the formula to softmax is not rendered correctly 

### ISSUE THREAD

**Issue by mhamri** [jeffheaton/t81_558_deep_learning#112]
in https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_03_1_neural_net.ipynb

the softmax function doesn't show correctly
![image](https://user-images.githubusercontent.com/8991783/130106120-7f65af3d-f8a7-45b2-b756-923205472d3d.png)

**Comment by jeffheaton** [comment]
Thanks, just checked in correction.
