### ISSUE TITLE
Saving the model

### ISSUE THREAD

**Issue by zaky9** [jeffheaton/t81_558_deep_learning#113]
Hi, may I know how to save the model? im trying to use pickle since keras model is also included, I couldnt save it. Are there any other approach? Thank you

**Comment by jeffheaton** [comment]
See:

https://stackoverflow.com/questions/42763094/how-to-save-final-model-using-keras

My course covers it here:
https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_03_3_save_load.ipynb

https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_13_02_checkpoint.ipynb
