### ISSUE TITLE
14.1 code errors

### ISSUE THREAD

**Issue by Hiertjy** [jeffheaton/t81_558_deep_learning#117]
Thanks for the great tutorials. I get unexpected errors with the code in "Part 14.1: What is AutoML", particularly if I try the regression example. Is there a simple fix?

**Comment by jeffheaton** [comment]
What error?

**Comment by Hiertjy** [comment]
My apologies, rookie error.

I was not in the right environment.

Thanks for the prompt reply though.

**Comment by Chosseppe** [comment]
Hello. I am dealing with this error messages and do not know how to deal with it 

[I 09:41:59.245 NotebookApp] Replaying 3 buffered messages
2021-09-23 09:42:42.640198: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-09-23 09:42:42.642025: W tensorflow/core/platform/profile_utils/cpu_utils.cc:126] Failed to get CPU frequency: 0 Hz
2021-09-23 09:42:42.646548: F tensorflow/core/grappler/costs/op_level_cost_estimator.cc:710] Check failed: 0 < gflops (0 vs. 0)type: "CPU"
model: "0"
num_cores: 8
environment {
  key: "cpu_instruction_set"
  value: "ARM NEON"
}
environment {
  key: "eigen"
  value: "3.3.90"
}
l1_cache_size: 16384
l2_cache_size: 524288
l3_cache_size: 524288
memory_size: 268435456

**Comment by jeffheaton** [comment]
I ran it myself, did get a few errors.  Stuff I introduced during reformatting, but got it to run through.  I checked in the changes.

**Comment by Chosseppe** [comment]
> I ran it myself, did get a few errors. Stuff I introduced during reformatting, but got it to run through. I checked in the changes.

I am going to try it again but it felt down with message kernel has died

**Comment by Chosseppe** [comment]
I just reinstalled whole enviro and now i took new error messages. But now training has started

**Comment by naruto112** [comment]
Hi @jeffheaton 
how are you ?

I have a problem mentioned by this function

`---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-79-d152560ca122> in <module>()
----> 1 train(train_dataset, EPOCHS)

<ipython-input-61-91be831f9292> in train(dataset, epochs)
     15       disc_loss_list.append(t[1])
     16 
---> 17     g_loss = sum(gen_loss_list) / len(gen_loss_list)
     18     d_loss = sum(disc_loss_list) / len(disc_loss_list)
     19 

ZeroDivisionError: division by zero`

help me ?

**Comment by jeffheaton** [comment]
Kernel die is usually an install issue or a GPU resource issue.  There is not too much I can do for that, unless I can reproduce it on my side.
