### ISSUE TITLE
Module 3 syntax mistake

### ISSUE THREAD

**Issue by mikdvdv** [jeffheaton/t81_558_deep_learning#121]
Thank you for your course! It is amazing! But I have found a little issue in the Module 3
In[11]: 
```python
# Sample predictions
for i in range(10):
    print(f"{i+1}. Car name: {cars[i]}, MPG: {y[i]}, " 
          + "predicted MPG: {pred[i]}")
```
f is missing, so the output has "pred[i]" in it
I hope It helps.

**Comment by jeffheaton** [comment]
Thank you!
