### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by naruto112** [jeffheaton/t81_558_deep_learning#122]
Hi @jeffheaton
how are you ?

I have a problem mentioned by this function

![135191916-603ffd7c-6ce2-4629-8edb-558e2f37658c](https://user-images.githubusercontent.com/9589702/135192092-1af524e0-93e1-4215-8c1c-611793559e74.png)

Error log:

![135191760-590d744d-523c-4ce5-a433-ad5efd56d06d](https://user-images.githubusercontent.com/9589702/135192126-7e01fb47-02db-4df3-b77d-8336102b7e95.png)

help me ?

**Comment by naruto112** [comment]
in trial and error I discovered the problem.

[RESOLVED]

This is because I was pointing to the empty folder with no image for training
![Captura de Tela 2021-09-28 às 23 50 43](https://user-images.githubusercontent.com/9589702/135194945-cb0da13e-b685-4b84-a808-946cccb412d1.png)
.

**Comment by jeffheaton** [comment]
Which of my files are you reporting a bug on?  Could you give me a link to Git? I am not recognizing this code, off hand.
