### ISSUE TITLE
Error: NameError Traceback (most recent call last)

### ISSUE THREAD

**Issue by naruto112** [jeffheaton/t81_558_deep_learning#124]
Hi @jeffheaton how are you ?

I'm trying to run this training function and it generates this error after 60 minutes running. Can you help me ?

![Captura de Tela 2021-09-29 às 18 53 17](https://user-images.githubusercontent.com/9589702/135354033-975cf775-d0c7-4bbd-9d4c-7e8ae5555418.png)

**Comment by jeffheaton** [comment]
Which file in the repo are you reporting this issue on?

**Comment by jeffheaton** [comment]
The error means exactly what it says "hms_string" is not defined.  Make sure that you executed all previous cells.  

```
# Nicely formatted time string
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return f"{h}:{m:>02}:{s:>05.2f}"
```

**Comment by naruto112** [comment]
> O erro significa exatamente o que diz "hms_string" não está definido. Certifique-se de ter executado todas as células anteriores.
> 
> ```
> # Nicely formatted time string
> def hms_string(sec_elapsed):
>     h = int(sec_elapsed / (60 * 60))
>     m = int((sec_elapsed % (60 * 60)) / 60)
>     s = sec_elapsed % 60
>     return f"{h}:{m:>02}:{s:>05.2f}"
> ```

Hi @jeffheaton  

Thanks very much ... 
I hadn't seen this function... I'm running again
