### ISSUE TITLE
generating high quality faces with gans

### ISSUE THREAD

**Issue by ms0017** [jeffheaton/t81_558_deep_learning#125]
Dear Dr. Heaton,

I have been following your teachings closely on YouTube, and I would like to use this opportunity to share my genuine appreciation for all the amazing contents, resources, and knowledge you are making available to the world.

One of my favorite repo's of all time is your work on [style gans](https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_07_3_style_gan.ipynb), particularly the face generation aspect of it.

It would be greatly appreciated by the learning community if you could suggest how to create high resolution images (at lease 1024x1024 pixels [could be an idea for your next YouTube video :)]) with the current code base that you have established. 

Nvidia uses the [same pretrained model as you](https://drive.google.com/drive/folders/1yanUI9m4b4PWzR0eurKNq6JR1Bbfbh6L), I believe, to generated [hd images](https://drive.google.com/drive/folders/1mTeo3J3Jo6aYImBshLM6XRl_Ua8fqgVW), so I a little lost on why hd images are not generated with this process also.

I understand you are extremely busy, but this would be a great resource to share with your 'students' if you can make the time. Thanks!

**Comment by jeffheaton** [comment]
I did end up creating a video on this.  Greater than 1024 is problematic with current StyleGAN code.  

https://www.youtube.com/watch?v=0q-38tHoz1s
