### ISSUE TITLE
Model unable to train (CNN doesn’t work)

### ISSUE THREAD

**Issue by yibingtan** [jeffheaton/t81_558_deep_learning#126]
Hello, I have followed this website: https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb on how to install tensorflow on my macbook. However, my code stops when I try to run CNN and LSTM. 

My cell will be marked as completed but I will still be at epoch 1 /3.  Then the whole code will fail.

This is where I get the code from: https://keras.io/examples/nlp/text_classification_from_scratch/
<img width="986" alt="Screenshot 2021-10-13 at 10 02 54 PM" src="https://user-images.githubusercontent.com/85612320/137169138-c14fed34-081b-4394-b492-6ec4e3d15306.png">

**Comment by jeffheaton** [comment]
I cannot really provide support for the code on kerias.io, it is not my creation.  The error that you have suggestions you did not copy/paste the like where the model is defined, make sure you include everything.  Have a particular look at:

```
model = tf.keras.Model(inputs, predictions)
```

As this defines "model" which is causing you your error above.
