### ISSUE TITLE
The kernel appears to have died.

### ISSUE THREAD

**Issue by sohil-hub** [jeffheaton/t81_558_deep_learning#127]
When I tried to run **import tensorflow as tf**, I got a message that the kernel appears to have died.

When I tried to import TensorFlow in the terminal without jupyter I got the message **killed python**.

I have installed TensorFlow according to the same notebook before and have been using it for a long, but because of some problems I had to reinstall both homebrew and mini forge, after that, I am not able to use TensorFlow.

Notebook link:- https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb

<img width="748" alt="Screenshot 2021-10-24 at 10 13 13 PM" src="https://user-images.githubusercontent.com/79828293/138604060-acf210d9-f1a8-4bac-aaf6-f713f0bf8c37.png">
<img width="1043" alt="Screenshot 2021-10-24 at 10 15 25 PM" src="https://user-images.githubusercontent.com/79828293/138604175-28210c7a-f775-45fb-860c-707402789656.png">
)

**Comment by muhammad-zahir** [comment]
Hi, yes I am having the same issue. I have followed the instructions exactly as mentioned but Everytime I try to import tensforflow the kernel dies and restarts automatically? Will be great for a solution as this has been effecting me for months now
