### ISSUE TITLE
Intel install guidelines missing

### ISSUE THREAD

**Issue by JulienVincenot** [jeffheaton/t81_558_deep_learning#131]
Hello, 

I see on tensorflow-install-mac-metal-jul-2021.ipynb that the link mentioned options for Intel macs is not functioning anymore.

Is it still realistic to try and work with those models? I won't have access to an M1 mac for a while. Thanks !

**Comment by jeffheaton** [comment]
Since my Intel Mac died, I somewhat have the opposite problem.  However, here are the instructions that I had from my Intel Mac days:

https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-jan-2021.ipynb

**Comment by JulienVincenot** [comment]
Hi Jeff

Thank you for the link. But somewhere on the page you say :
"The following instructions install TensorFlow onto a Mac with no hardware acceleration (GPU)."

Does this mean Intel macs cannot use even beefier internal GPUS (I have a AMD Radeon Pro 5500M with 8Gb) for deep learning experimentations?

In this case I don't understand, I did managed a few days ago to start a test on my machine, following another of your video tutorials for M1 and [this article](https://towardsdatascience.com/accelerated-tensorflow-model-training-on-intel-mac-gpus-aa6ee691f894), and adapting to Intel somehow. The main issue was hooking up the correct Python version (3.8.10 is the only one that worked for me)

GPU seems to activate and the code runs through epochs at "plausible" speed (I guess?), see screenshot here on https://ibb.co/5MDYJq0 
But the issue is that many TS functions return always the same error : 
"Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support."
so it is practically impossible to follow regular TensorFlow tutorials to learn. It's like only the final calculations works, but intermediary steps cannot. Or worst, the code makes the GPU "believe" it's working on something, but it actually produces nothing except heat...

Per chance, maybe some of your students were still able to use GPU acceleration on Intel macs successfully?
Thanks in advance for your help !

**Comment by jeffheaton** [comment]
They might be able to, with the right settings. But I lack the hardware to try out AMD acceleration options.

**Comment by jeffheaton** [comment]
Added intel instruction link here:
* http://localhost:8888/notebooks/t81_558_class_01_1_overview.ipynb

Note, my last Intel mac died a few months back, so my ability to support Intel Mac no longer exists.
