### ISSUE TITLE
Input variable not being used

### ISSUE THREAD

**Issue by lewiuberg** [jeffheaton/t81_558_deep_learning#132]
**Describe the bug**
The input variable `img_file` is being used. It looks like it should substitute `LOCAL_IMG_FILE` to function correctly.

**Expected behavior**
Enabeling the function to process different URLs directly, not only the previously processed variable.

**Which Notebook Contains this Issue**
[t81_558_deep_learning/t81_558_class_06_4_keras_images.ipynb](https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_06_4_keras_images.ipynb)

**Comment by jeffheaton** [comment]
Good catch, thanks!  Checked in fix.
