### ISSUE TITLE
Error when running the code 

### ISSUE THREAD

**Issue by Ishaanjolly** [jeffheaton/t81_558_deep_learning#135]
Hi, I was trying to run the code here: [
](https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_03_2_keras.ipynb) 

But got the following error: 
NotFoundError: No registered 'AssignVariableOp' OpKernel for 'GPU' devices compatible with node {{node AssignVariableOp}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: dtype=DT_COMPLEX64
	.  Registered:  device='GPU'; dtype in [DT_FLOAT]
  device='GPU'; dtype in [DT_INT64]
  device='GPU'; dtype in [DT_UINT64]
  device='GPU'; dtype in [DT_BOOL]
  device='GPU'; dtype in [DT_HALF]
  device='GPU'; dtype in [DT_DOUBLE]
  device='CPU'; dtype in [DT_UINT64]
  device='CPU'; dtype in [DT_INT64]
  device='CPU'; dtype in [DT_UINT32]
  device='CPU'; dtype in [DT_UINT16]
  device='CPU'; dtype in [DT_INT16]
  device='CPU'; dtype in [DT_UINT8]
  device='CPU'; dtype in [DT_INT8]
  device='CPU'; dtype in [DT_INT32]
  device='CPU'; dtype in [DT_HALF]
  device='CPU'; dtype in [DT_BFLOAT16]
  device='CPU'; dtype in [DT_FLOAT]
  device='CPU'; dtype in [DT_DOUBLE]
  device='CPU'; dtype in [DT_COMPLEX64]
  device='CPU'; dtype in [DT_COMPLEX128]
  device='CPU'; dtype in [DT_BOOL]
  device='CPU'; dtype in [DT_STRING]
  device='CPU'; dtype in [DT_RESOURCE]
  device='CPU'; dtype in [DT_VARIANT]
  device='CPU'; dtype in [DT_QINT8]
  device='CPU'; dtype in [DT_QUINT8]
  device='CPU'; dtype in [DT_QINT32]
 [Op:AssignVariableOp]
https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_01_1_overview.ipynb)

I think likely cause of this might be the tensorflow installation on M1 mac (I followed the instructions on Jeff's YouTube video)

**Comment by jeffheaton** [comment]
Unfortunately, I do not have the capacity to help on individual installs.  You might try Colab, the code on module 1.1 works okay there.
