### ISSUE TITLE
conda env error never be found before. How to solve this?

### ISSUE THREAD

**Issue by Lyrics1997** [jeffheaton/t81_558_deep_learning#137]
I face some errors never be found before

1.  My python address is /usr/bin/python, not similar to  /opt/homebrew/Caskroom/miniforge/base/bin/python

2. After run the command: 'conda env create -f tensorFlow-apple-metal.yml -n tensorflow'. I face the error: 'SpecNotFound: Invalid name, try the format: user/package' 

Thanks in advance!

**Comment by Lyrics1997** [comment]
First question has been solved.

**Comment by jeffheaton** [comment]
I tried to reproduce this issue, but was unable to.  I am not sure if this is related to not using brew, or not. You might try running the YAML lines manually, one-by-one and see which is giving an issue.  Unfortunately, I really do not have the capacity to investigate individual issues with system installs.

**Comment by hussainakram** [comment]
No need to use `env` in the command
just run the following:
```
conda create -f tensorflow-apple-metal.yml -n tensorflow
```

Reference: https://stackoverflow.com/a/38130515/19183299
