### ISSUE TITLE
Possible missing argument

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [jeffheaton/t81_558_deep_learning#139]
Hi there, thank you for your tutorial, I would like just to point out that on my new MacBook Pro (M1 Max), at [this step](https://github.com/jeffheaton/t81_558_deep_learning/blob/753171f6e52855de674996d1a17bcfa979514365/install/tensorflow-install-mac-metal-jul-2021.ipynb?short_path=c52ea59#L66-L68)
instead of `conta init` I had to run `conda init zsh` (alternatively there is also `bash`), in order to have the env correctly setup... idk if this happened also to others, maybe it was because I also have Anaconda

**Comment by jeffheaton** [comment]
Thanks, I could see this coming up in some cases.  I will add it to the instructions soon.

**Comment by jeffheaton** [comment]
Added note.
