### ISSUE TITLE
titles of notebooks.. 

### ISSUE THREAD

**Issue by alphaBenj** [jeffheaton/t81_558_deep_learning#14]
Can you please rename notebooks 
from:
t81_558_class1_intro_python.ipynb
to:
t81_558_class01_intro_python.ipynb

easier to follow... watched repo three years! best repo on topic!

**Comment by jeffheaton** [comment]
That is a good idea.  I will make that change soon.  Just have to find any links that breaks.

**Comment by jeffheaton** [comment]
Done, thanks for the suggestion.
