### ISSUE TITLE
Problem running the TensorFlow-apple-metal.yml script

### ISSUE THREAD

**Issue by Michaelislab** [jeffheaton/t81_558_deep_learning#140]
**Describe the bug**

I tried to execute the TensorFlow-apple-metal.yml script. It returns the following error:     
 File "/Users/jensmichaelis/miniforge3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 651, in fetch_value
        raise ScannerError(
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 25, column 67:
         ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ... 
                                             ^ (line: 25)

`$ /Users/jensmichaelis/miniforge3/bin/conda-env create -f tensorflow-apple-metal.yml -n tensorflow`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
                CONDA_EXE=/Users/jensmichaelis/miniforge3/bin/conda
         CONDA_PYTHON_EXE=/Users/jensmichaelis/miniforge3/bin/python
               CONDA_ROOT=/Users/jensmichaelis/miniforge3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/jensmichaelis/miniforge3/bin:/Users/jensmichaelis/miniforge3/co
                          ndabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/opt/X
                          11/bin:/Library/Apple/usr/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

**Expected behavior**
I wanted to install TensorFlow on my M1pro Mac. I was following the instructions from the youtube video https://www.youtube.com/watch?v=w2qlou7n7MA

**Which Notebook Contains this Issue**
Error occurred in this notebook:
https://github.com/jeffheaton/t81_558_deep_learning/blob/master/tensorflow-apple-metal.yml

**Comment by jeffheaton** [comment]
I am able to run the script without error. I have not encountered this error.  My apologies, but I do not have time to investigate individual installations.
