### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow>=2.4.0

### ISSUE THREAD

**Issue by rio26** [jeffheaton/t81_558_deep_learning#141]
Hi, thank you very much for the tutorial.

I have followed your tutorial and got all the command lines similar to the youtube video you posted online.
**"tf.version.VERSION" shows: "tensforflow version:  2.5.0".**

However,  when I try to install the "GPflow" package, I got the following errors:
"pip install git+https://github.com/GPflow/GPflow.git@develop#egg=gpflow
Collecting gpflow
  Cloning https://github.com/GPflow/GPflow.git (to revision develop) to /private/var/folders/89/_w_b_0l92q30vllyqlp1n2k40000gn/T/pip-install-0u0vauf5/gpflow_dd9497fed4e441b2a443a449d64c08fc
  Running command git clone --filter=blob:none --quiet https://github.com/GPflow/GPflow.git /private/var/folders/89/_w_b_0l92q30vllyqlp1n2k40000gn/T/pip-install-0u0vauf5/gpflow_dd9497fed4e441b2a443a449d64c08fc
  Resolved https://github.com/GPflow/GPflow.git to commit 86352c46552dd4b2db7dfe4e8d1b33093f88b909
  Preparing metadata (setup.py) ... done
Collecting deprecated
  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting lark>=1.1.0
  Using cached lark-1.1.2-py2.py3-none-any.whl (104 kB)
Requirement already satisfied: multipledispatch>=0.6 in /Users/rio/miniforge3/envs/tensorflow/lib/python3.9/site-packages (from gpflow) (0.6.0)
Requirement already satisfied: numpy in /Users/rio/miniforge3/envs/tensorflow/lib/python3.9/site-packages (from gpflow) (1.22.3)
Requirement already satisfied: packaging in /Users/rio/miniforge3/envs/tensorflow/lib/python3.9/site-packages (from gpflow) (21.3)
Requirement already satisfied: scipy in /Users/rio/miniforge3/envs/tensorflow/lib/python3.9/site-packages (from gpflow) (1.7.3)
Requirement already satisfied: setuptools>=41.0.0 in /Users/rio/miniforge3/envs/tensorflow/lib/python3.9/site-packages (from gpflow) (58.0.4)
Collecting tabulate
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting tensorflow-probability>=0.12.0
  Using cached tensorflow_probability-0.16.0-py2.py3-none-any.whl (6.3 MB)
**ERROR: Could not find a version that satisfies the requirement tensorflow>=2.4.0 (from gpflow) (from versions: none)
ERROR: No matching distribution found for tensorflow>=2.4.0**
"

When I type "pip list", I saw the TensorFlow related packages listed as:
"
...
tensorboard              2.8.0
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
tensorflow-datasets      4.5.2
tensorflow-estimator     2.5.0
tensorflow-macos         2.5.0
tensorflow-metadata      1.7.0
tensorflow-metal         0.1.2
...
"
**I did not see tensorflow, but only "tensorflow-macos 2.5.0" listed above.**

I tried to check with pip:

% pip3 show tensorflow-macos
Name: tensorflow-macos
Version: 2.5.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/rio/miniforge3/envs/tensorflow/lib/python3.9/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras-nightly, keras-preprocessing, numpy, opt-einsum, protobuf, six, tensorboard, tensorflow-estimator, termcolor, typing-extensions, wheel, wrapt
Required-by: 

% pip3 show tensorflow    
WARNING: Package(s) not found: tensorflow

Is it possibly because the name wasn't recognized by pip? 
Do you have any suggestions on how to fix these errors:
"
ERROR: Could not find a version that satisfies the requirement tensorflow>=2.4.0 (from gpflow) (from versions: none)
ERROR: No matching distribution found for tensorflow>=2.4.0
"

Any suggestions would be greatly appreciated!

**Comment by jeffheaton** [comment]
I've not run into this problem, there must be something preventing your system from using a later version TensorFlow, maybe try 2.4?  Unfortunately, I don't really have time to address individual installation issues that I cannot easily replicate myself.

**Comment by jeffheaton** [comment]
I was able to successfully install with the provided steps.  Mac setups are a bit tricky and evolving. I really am not able to help troubleshoot issues I cannot reproduce.
