### ISSUE TITLE
Software Installation (Mac on Apple Metal M1) may need to update

### ISSUE THREAD

**Issue by qiulang** [jeffheaton/t81_558_deep_learning#144]
Software Installation (Mac on Apple Metal M1) may need to update.  For example we may not miniforge as conda has [Native M1 Support]( https://www.anaconda.com/blog/new-release-anaconda-distribution-now-supporting-m1) now.

I record my experience with that in https://stackoverflow.com/questions/72964800/what-is-the-proper-way-to-install-tensorflow-on-apple-m1-in-2022

**Comment by jeffheaton** [comment]
Thanks, I will be looking into this soon.  I would prefer to keep all platforms unified on CONDA.

**Comment by jeffheaton** [comment]
Good suggestion! Everything has been updated to conda!
