### ISSUE TITLE
remove 'env' from 'conda env create...' in installation guide

### ISSUE THREAD

**Issue by jpcompartir** [jeffheaton/t81_558_deep_learning#150]
Hi, 

Thanks for this repo-  the installation guide is extremely helpful in dealing with common Mac Mx issues, there's a teeny tiny error in the installation guide of this [notebook](https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb):.

"conda env create -f tensorflow-apple-metal.yml -n tensorflow"

I believe should be changed to:

"conda create -f tensorflow-apple-metal.yml -n tensorflow"

Thanks!

**Comment by jeffheaton** [comment]
I tried it as I have it, and it seems to work.  I believe the command is valid either way, just to keep it consistant with my video I will leave it as I have it.
