### ISSUE TITLE
Keras needs to be replaced with PyTorch in 3_3

### ISSUE THREAD

**Issue by TJ-C** [jeffheaton/t81_558_deep_learning#152]
**Describe the bug**
Part 3.3: Saving and Loading a Keras Neural Network 

**Expected behavior**
Part 3.3: Saving and Loading a PyTorch Neural Network

**Which Notebook Contains this Issue**
https://github.com/jeffheaton/t81_558_deep_learning/blob/pytorch/t81_558_class_03_3_save_load.ipynb

**Comment by jeffheaton** [comment]
Thanks.
