### ISSUE TITLE
Running Early Stopping with Classification on an M1 Max early stop is not triggered 

### ISSUE THREAD

**Issue by TJ-C** [jeffheaton/t81_558_deep_learning#153]
**Describe the bug**
Running Early Stopping with Classification on an M1 Max early stop is not triggered because tloss & vloss are not changing:
Epoch: 1, tloss: 0.5526171326637268, vloss: 1.156877, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 26.63it/s]
Epoch: 2, tloss: 0.5514456629753113, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 98.73it/s]
Epoch: 3, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 109.15it/s]
Epoch: 4, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 105.33it/s]
Epoch: 5, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 110.84it/s]
Epoch: 6, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 108.64it/s]
Epoch: 7, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 108.95it/s]
Epoch: 8, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 112.16it/s]
Epoch: 9, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 112.19it/s]
Epoch: 10, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 109.70it/s]
Epoch: 11, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 108.13it/s]
Epoch: 12, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 109.21it/s]
Epoch: 13, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 110.22it/s]
Epoch: 14, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 110.11it/s]
Epoch: 15, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 107.90it/s]
Epoch: 16, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 109.56it/s]
Epoch: 17, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 107.53it/s]
Epoch: 18, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 110.37it/s]
Epoch: 19, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 109.00it/s]
Epoch: 20, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 109.90it/s]
Epoch: 21, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 106.88it/s]
Epoch: 22, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 108.25it/s]
Epoch: 23, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 111.08it/s]
Epoch: 24, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 110.19it/s]
Epoch: 25, tloss: 0.5514446496963501, vloss: 1.156708, EStop:[0/5]: 100%|██████████| 7/7 [00:00<00:00, 108.93it/s] 

**Expected behavior**
When running on Colab, works as expected 

**Which Notebook Contains this Issue**
https://github.com/jeffheaton/t81_558_deep_learning/blob/pytorch/t81_558_class_03_4_early_stop.ipynb

**Comment by Omni-Engineering** [comment]
🎖️

**Comment by jeffheaton** [comment]
PyTorch version is moving to its [own top level repo](https://github.com/jeffheaton/app_deep_learning), I made some fixes to the earlystopping, which hopefully address this. It seems to run okay on my Mac M2 at this point.
