### ISSUE TITLE
Running instalation step by step

### ISSUE THREAD

**Issue by Joseph-Mikalika** [jeffheaton/t81_558_deep_learning#154]
After running instalation of tensorflow 3. time i stil have problem with tensorflow

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [7], line 4
      1 # What version of Python do you have?
      2 import sys
----> 4 import tensorflow.keras
      5 import pandas as pd 
      6 import sklearn as sk

ModuleNotFoundError: No module named 'tensorflow'

**Comment by jeffheaton** [comment]
My apologies, but I cannot offer help for individual installations.  From that error, it appears you do not have the tensorflow package installed.

**Comment by Joseph-Mikalika** [comment]
problem is with numpy library in conda enviroment.

**Comment by Joseph-Mikalika** [comment]
and in tensorflow virtual enviroment was bad version of keras installed with tensorflow-macos.
