### ISSUE TITLE
Error: failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by kartik-binzade** [jeffheaton/t81_558_deep_learning#156]
im working on my academic project "**Malware Classification using Ember and AWS SageMaker**" 
i want to build a deploy model from aws SageMaker but it gives error.
Error:
1.loaded_model = model_from_json(loaded_model_json,custom_objects={"GlorotUniform": tf.keras.initializers.glorot_uniform})
   NameError: name 'model_from_json' is not defined

2.no CUDA-capable device is detected

3.kernel driver does not appear to be running on this host (ip------ec2.internal): /proc/driver/nvidia/version does not exist.

**Comment by jeffheaton** [comment]
I really have not worked with Sagemaker deploys in awhile. My apologies, but I do not have the bandwidth to offer individual support, for problems not related to the project that you posted this issue to.

**Comment by kartik-binzade** [comment]
Okay. Thank You Jeff.
