### ISSUE TITLE
Error: update_endpoint is a no-op in sagemaker>=2. See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.

### ISSUE THREAD

**Issue by kartik-binzade** [jeffheaton/t81_558_deep_learning#157]
**How can we solve this error please guide us.**

Error: update_endpoint is a no-op in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.

**deploy your model in SageMaker and create Real-time inference endpoint:**

from tensorflow.keras import backend
from sagemaker.tensorflow.model import TensorFlowModel
role = 'arn:aws:iam::ID:role/AmazonSageMaker-ExecutionRole-.........'
sagemaker_model = TensorFlowModel(model_data='s3://sagemaker-ap-south-1-ID/model/model.tar.gz',
                                  role = role,
                                  framework_version = '1.12',
                                  entry_point = 'train.py')

%%time
predictor = sagemaker_model.deploy(initial_instance_count=1,
                                   instance_type='ml.t3.medium')
print("Success!")
predictor.endpoint

**Comment by jeffheaton** [comment]
Apologies but I really do not have the bandwidth to help with individual issues.
