### ISSUE TITLE
Trying to install conda environment from yml file fails. Manual installation works fine

### ISSUE THREAD

**Issue by javedhassans** [jeffheaton/t81_558_deep_learning#158]
Please note, I do not have the time availability to help with individual installation requests. If you've noticed something that needs to be changed in the installation instructions, please report what you think needs to be changed. Generally, I rerun my installation instructions once a semester and make any adjustments needed at that point.

**Describe the bug**
Used the below command to install the environment from the environment.yml file
_**conda env create -f environment.yml**_ 
it fails

**Expected behavior**
The environment should have been installed.

**Which Notebook Contains this Issue**
environment.yml

**Comment by jeffheaton** [comment]
My apologies, I do not really have the bandwidth to help for individual installs. I update the install instructions once a semester to address any changes.
