### ISSUE TITLE
Error when fit model executes

### ISSUE THREAD

**Issue by sfernandezr** [jeffheaton/t81_558_deep_learning#163]
Hello!

I've successfully followed the instructions for installing TensorFlow on M1 MacBook Pro. 

To test if it works I've decided to run Jupyter Notebook: Chapter 14 of Hands On Machine Learning (https://github.com/ageron/handson-ml2/blob/master/14_deep_computer_vision_with_cnns.ipynb).

I get the following error when trying to fit a model: (Third cell under the section "Tackling Fashion MNIST With a CNN")

2023-03-06 20:47:37.960631: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-03-06 20:47:39.529029: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x7fad800f6810

Thank you!

**Comment by jeffheaton** [comment]
Why are you reporting this issue here? I am not the author of the notebook you are referencing.

**Comment by sfernandezr** [comment]
Sorry I didn't explained myself well. What I'm trying to say is that in my experience, even though I successfully installed the packages following your guide. When I execute any .fit function I receive the above error.

That Jupyter notebook code was just an example code where I execute the .fit function and receive the error. I don't believe the problems is on that particular code. I had the same issues on other codes as well, for example, in Tensorflow's guide for training built-in methods (https://www.tensorflow.org/guide/keras/train_and_evaluate).
