### ISSUE TITLE
regarding pytorch branch folder install file torch.yml (not sure if it is an issue)

### ISSUE THREAD

**Issue by fstylianou** [jeffheaton/t81_558_deep_learning#164]
In the pytorch-install-aug-2022.ipynb notebook to says the the torch.yml is for CPU only but this file has no difference with the torch-cuda.yml file. So how does the installation know if it is going to install a CPU or a CUDA version?

Thanks in advance.

**Comment by jeffheaton** [comment]
Moving PyTorch branch to its [own top level repo](https://github.com/jeffheaton/app_deep_learning), I will be reworking install directions.
