### ISSUE TITLE
CuDNN version conflict after following WSL install instructions

### ISSUE THREAD

**Issue by probit2011** [jeffheaton/t81_558_deep_learning#166]
Hi Jeff,

While not being a student of yours, I wanted to deepen my knowledge of neural networks using your videos and class materials. I have followed your instructions (https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-march-2023.ipynb) to install Tensorflow/Keras via WSL2. I have a NVIDIA GeForce GTX 1650 Ti card on my machine, which could allow me in theory to use CUDA 10.1.

**Describe the bug**
While I managed to complete the installation without any major issue, I have encountered a problem when I tried to work on the first Keras assignment (https://github.com/jeffheaton/t81_558_deep_learning/blob/master/assignments/assignment_yourname_class4.ipynb). I wrote a simple sequential model with two hidden layers and tried to execute it, but I received the following error message upon the calculations of the first epoch (shortened):

> 2023-05-19 20:33:13.168761: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:417] Loaded runtime CuDNN library: 8.1.0 but source was compiled with: 8.6.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
> 
> 2023-05-19 20:33:13.192458: E tensorflow/compiler/xla/status_macros.cc:57] INTERNAL: RET_CHECK failure (tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:618) dnn != nullptr  

There appears to be a version conflict for the CuDNN library (8.1.0 vs 8.6.0). I have checked that it is version 8.1.0 that is installed; however, it seems that something in Tensorflow caused 'source [to be] compiled with 8.6.0'?

I should also mention that while your instructions refer to installing Python 3.9, following the instructions to the letter led (in my case) to having Python 3.11 being installed in the WSL environment. I am not sure whether this might be an indirect cause of the CuDNN version conflict.

I would really appreciate if you could verify whether this is a bug arising from your instructions and/or if you could give some pointers on how to resolve the issue.

Best regards,

Patrick Robitaille
Sydney, Australia

**Comment by jeffheaton** [comment]
I generally do not provide support for installs, as they really can vary greatly to individual environments. I update the instructions one per semester, and will be doing so soon.
