### ISSUE TITLE
How to get the inverse of this function "encode_text_index (df, name)"?

### ISSUE THREAD

**Issue by FatenLoua** [jeffheaton/t81_558_deep_learning#17]
Hello sir,
How to get the opposite of this function "encode_text_index (df, name)", I mean how to know that 0 is the class normal and 1 is a DoS for example? because the result only displays the code of each class (0, 1, 2, 3, 4) I want to know the name of the class, how to do it?
Thank you.﻿

**Comment by jeffheaton** [comment]
This is what the return value of "encode_text_index" is for.  See class 3:

I do this to keep the species of iris:

`species = encode_text_index(df,"species")`

Then I do something like this to turn the species #'s back into text.

`print(species[predict_classes[1:10]])`
