### ISSUE TITLE
Typo in notebook t81_558_class09_regularization.ipynb

### ISSUE THREAD

**Issue by Brotherlui** [jeffheaton/t81_558_deep_learning#20]
Hi Jeff, in notebook t81_558_class09_regularization.ipynb, chapter "TensorFlow and L1/L2", the last sentence above the "L1 vs L2" graph, "**L1** will force the weights into a pattern similar to a **Gaussian** distribution; the **L2** will force the weights into a pattern similar to a **Laplace** distribution, as demonstrated the following:". It is actually vice-versa and correctly labeled in the graph.

**Comment by jeffheaton** [comment]
Thanks, checked in correction.
