### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow==1.12.0

### ISSUE THREAD

**Issue by adhirmndl** [jeffheaton/t81_558_deep_learning#24]
![conda](https://user-images.githubusercontent.com/17833384/55937133-d8c0cb80-5c55-11e9-8bf0-86d47e6db476.jpg)

Please help ..

**Comment by JafferWilson** [comment]
You are using Python 3.6. Try installing through wheel file : https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl
Read this: https://www.tensorflow.org/install/pip
And close this issue please.

**Comment by jeffheaton** [comment]
Yes, @JafferWilson suggestion should work.
