### ISSUE TITLE
Simple TensorFlow LSTM Example

### ISSUE THREAD

**Issue by alphaBenj** [jeffheaton/t81_558_deep_learning#25]
On the example -- listed as cell number 9. 

```
max_features = 4 # 0,1,2,3 (total of 4)
x = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[2],[2],[0]],
    [[0],[0],[0],[0],[3],[3]],
    [[0],[2],[2],[0],[0],[0]],
    [[0],[0],[3],[3],[0],[0]],
    [[0],[0],[0],[0],[1],[1]]
]
x = np.array(x,dtype=np.float32)
y = np.array([1,2,3,2,3,1],dtype=np.int32)

```
can x be represented as two 'block/arrays'
one being the length in the "window" and second being a one-hot encoded array of color. 

```
x2 = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[1],[1],[0]],
    [[0],[0],[0],[0],[1],[1]],
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[1],[1],[0],[0]],
    [[0],[0],[0],[0],[1],[1]]
]
x3 = [
    [[1],[0],[0]],
    [[0],[1],[0]],
    [[0],[0],[1]],
    [[0],[1],[0]],
    [[0],[0],[1]],
    [[1],[0],[0]]
]

```
This thought comes form using with the blank data array  [[0],[0],[0],[0],[0],[0]], the one decision is where to start the sequence,  the second is what color.  But, combining the two array, give the incorrect length in the starting array of seven elements. 

I can be reached at newbox dot me at gmail dot com. thanks

**Comment by jeffheaton** [comment]
I've never tried it that way, seems like additional memory used.  I am not really seeing an advantage.  Did it work well?

**Comment by alphaBenj** [comment]
good morning, 

I havent able to try because I dont know how to setup the array in away to process with LSTM method, 
If I test current method shown, it gives errant answers.  So, seeing if this help in giving better answers. 

Can you assist with help setting up this structure? thanks.
