### ISSUE TITLE
Running Automl Error

### ISSUE THREAD

**Issue by TshepoMK** [jeffheaton/t81_558_deep_learning#32]
is .lower() method supposed to be for column names or the entire dataframe

`AttributeError: 'DataFrame' object has no attribute 'lower'`

**Comment by jeffheaton** [comment]
I will have a look.

**Comment by jeffheaton** [comment]
I assume this is on file:
https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_14_01_automl.ipynb

But I am not seeing any calls to lower that would result in this error.  What file/line are you referring to?
