### ISSUE TITLE
NameError: name 'image_shape' is not defined

### ISSUE THREAD

**Issue by lars1990** [jeffheaton/t81_558_deep_learning#38]
Hey,

when building the Generator and the Discriminator with the Adam optimizer I receive the following error:

NameError                                 Traceback (most recent call last)

<ipython-input-3-fc128f4839ef> in <module>()
    163 optimizer = Adam(1.5e-4,0.5) # learning rate and momentum adjusted from paper
    164 
**--> 165 discriminator = build_discriminator(image_shape)**
    166 discriminator.compile(loss="binary_crossentropy",optimizer=optimizer,metrics=["accuracy"])
    167 generator = build_generator(SEED_SIZE,IMAGE_CHANNELS)

NameError: name 'image_shape' is not defined

How could I solve this problem?

**Comment by jeffheaton** [comment]
I will take a look at this soon.  Getting ready to clean up any issues/fixes ahead of the next semester.

**Comment by jeffheaton** [comment]
This should have been resolved with my previous checkin.
