### ISSUE TITLE
Unable to download the tensorflow

### ISSUE THREAD

**Issue by ashutos-lab** [jeffheaton/t81_558_deep_learning#57]
`
(base) C:\Users\admin>conda env create -v -f tensorflow.yml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda

initializing UnlinkLinkTransaction with
  target_prefix: C:\Users\admin\miniconda3\envs\tensorflow
  unlink_precs:

  link_precs:
    defaults/win-64::_tflow_select-2.2.0-eigen
    defaults/win-64::blas-1.0-mkl
    defaults/win-64::ca-certificates-2020.1.1-0
    defaults/win-64::icc_rt-2019.0.0-h0cc432a_1
    defaults/win-64::intel-openmp-2020.0-166
    defaults/win-64::msys2-conda-epoch-20160418-1
    defaults/win-64::pandoc-2.2.3.2-0
    defaults/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
    defaults/win-64::winpty-0.4.3-4
    defaults/win-64::m2w64-gmp-6.1.0-2
    defaults/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
    defaults/win-64::mkl-2020.0-166
    defaults/win-64::vc-14.1-h0510ff6_4
    defaults/win-64::icu-58.2-ha66f8fd_1
    defaults/win-64::jpeg-9b-hb83a4c4_2
    defaults/win-64::libiconv-1.15-h1df5818_7
    defaults/win-64::libsodium-1.0.16-h9d3ae62_0
    defaults/win-64::m2w64-gcc-libs-core-5.3.0-7
    defaults/win-64::openssl-1.1.1f-he774522_0
    defaults/win-64::sqlite-3.31.1-he774522_0
    defaults/win-64::tk-8.6.8-hfa6e2cd_0
    defaults/win-64::xz-5.2.5-h62dcd97_0
    defaults/win-64::yaml-0.1.7-hc54c509_2
    defaults/win-64::zlib-1.2.11-h62dcd97_4
    defaults/win-64::hdf5-1.10.4-h7ebc959_0
    defaults/win-64::libpng-1.6.37-h2a8f88b_0
    defaults/win-64::libprotobuf-3.11.4-h7bd577a_0
    defaults/win-64::libxml2-2.9.9-h464c3ec_0
    defaults/win-64::m2w64-gcc-libgfortran-5.3.0-6
    defaults/win-64::python-3.7.7-h60c2a47_2
    defaults/win-64::zeromq-4.3.1-h33f27b4_3
    defaults/win-64::zstd-1.3.7-h508b16e_0
    defaults/win-64::asn1crypto-1.3.0-py37_0
    defaults/win-64::astor-0.8.0-py37_0
    defaults/noarch::attrs-19.3.0-py_0
    defaults/win-64::backcall-0.1.0-py37_0
    defaults/win-64::blinker-1.4-py37_0
    defaults/noarch::cachetools-3.1.1-py_0
    defaults/win-64::certifi-2020.4.5.1-py37_0
    defaults/win-64::chardet-3.0.4-py37_1003
    defaults/noarch::click-7.1.1-py_0
    defaults/noarch::colorama-0.4.3-py_0
    defaults/noarch::decorator-4.4.2-py_0
    defaults/noarch::defusedxml-0.6.0-py_0
    defaults/win-64::docutils-0.15.2-py37_0
    defaults/win-64::entrypoints-0.3-py37_0
    defaults/win-64::freetype-2.9.1-ha9979f8_1
    defaults/win-64::gast-0.2.2-py37_0
    defaults/noarch::idna-2.9-py_1
    defaults/win-64::ipython_genutils-0.2.0-py37_0
    defaults/win-64::itsdangerous-1.1.0-py37_0
    defaults/noarch::jmespath-0.9.4-py_0
    defaults/win-64::kiwisolver-1.1.0-py37ha925a31_0
    defaults/win-64::libtiff-4.1.0-h56a325e_0
    defaults/win-64::libxslt-1.1.33-h579f668_0
    defaults/win-64::m2w64-gcc-libs-5.3.0-7
    defaults/win-64::markupsafe-1.1.1-py37he774522_0
    defaults/win-64::mistune-0.8.4-py37he774522_0
    defaults/win-64::olefile-0.46-py37_0
    defaults/win-64::pandocfilters-1.4.2-py37_1
    defaults/noarch::parso-0.6.2-py_0
    defaults/win-64::pickleshare-0.7.5-py37_0
    defaults/noarch::prometheus_client-0.7.1-py_0
    defaults/noarch::pyasn1-0.4.8-py_0
    defaults/noarch::pycparser-2.20-py_0
    defaults/noarch::pyparsing-2.4.6-py_0
    defaults/win-64::pyreadline-2.1-py37_1
    defaults/noarch::pytz-2019.3-py_0
    defaults/win-64::pywin32-227-py37he774522_1
    defaults/win-64::pyyaml-5.3.1-py37he774522_0
    defaults/win-64::pyzmq-18.1.1-py37ha925a31_0
    defaults/win-64::qt-5.9.7-vc14h73c81de_0
    defaults/noarch::qtpy-1.9.0-py_0
    defaults/win-64::send2trash-1.5.0-py37_0
    defaults/win-64::sip-4.19.8-py37h6538335_0
    defaults/win-64::six-1.14.0-py37_0
    defaults/win-64::termcolor-1.1.0-py37_1
    defaults/noarch::testpath-0.4.4-py_0
    defaults/win-64::tornado-6.0.4-py37he774522_1
    defaults/noarch::tqdm-4.44.1-py_0
    defaults/noarch::wcwidth-0.1.9-py_0
    defaults/win-64::webencodings-0.5.1-py37_1
    defaults/noarch::werkzeug-0.16.1-py_0
    defaults/win-64::win_inet_pton-1.1.0-py37_0
    defaults/win-64::wincertstore-0.2-py37_0
    defaults/win-64::wrapt-1.12.1-py37he774522_1
    defaults/noarch::zipp-2.2.0-py_0
    defaults/win-64::absl-py-0.9.0-py37_0
    defaults/win-64::cffi-1.14.0-py37h7a1dbc1_0
    defaults/win-64::cycler-0.10.0-py37_0
    defaults/noarch::google-pasta-0.2.0-py_0
    defaults/win-64::importlib_metadata-1.5.0-py37_0
    defaults/win-64::jedi-0.16.0-py37_1
    defaults/win-64::lxml-4.5.0-py37h1350720_0
    defaults/win-64::mkl-service-2.3.0-py37hb782905_0
    defaults/win-64::pillow-7.0.0-py37hcc1f983_0
    defaults/noarch::pyasn1-modules-0.2.7-py_0
    defaults/win-64::pyqt-5.9.2-py37h6538335_2
    defaults/win-64::pyrsistent-0.16.0-py37he774522_0
    defaults/win-64::pysocks-1.7.1-py37_0
    defaults/noarch::python-dateutil-2.8.1-py_0
    defaults/win-64::pywinpty-0.5.7-py37_0
    defaults/noarch::rsa-4.0-py_0
    defaults/win-64::setuptools-46.1.3-py37_0
    defaults/win-64::traitlets-4.3.3-py37_0
    defaults/noarch::bleach-3.1.4-py_0
    defaults/win-64::cryptography-2.8-py37h7a1dbc1_0
    defaults/noarch::google-auth-1.13.1-py_0
    defaults/win-64::grpcio-1.27.2-py37h351948d_0
    defaults/noarch::jinja2-2.11.1-py_0
    defaults/noarch::joblib-0.14.1-py_0
    defaults/win-64::jsonschema-3.2.0-py37_0
    defaults/win-64::jupyter_core-4.6.3-py37_0
    defaults/win-64::markdown-3.1.1-py37_0
    defaults/win-64::numpy-base-1.18.1-py37hc3f5095_1
    defaults/win-64::protobuf-3.11.4-py37h33f27b4_0
    defaults/noarch::pygments-2.6.1-py_0
    defaults/win-64::terminado-0.8.3-py37_0
    defaults/win-64::wheel-0.34.2-py37_0
    defaults/noarch::flask-1.1.2-py_0
    defaults/noarch::jupyter_client-6.1.2-py_0
    defaults/noarch::nbformat-5.0.4-py_0
    defaults/win-64::pip-20.0.2-py37_1
    defaults/noarch::prompt-toolkit-3.0.4-py_0
    defaults/win-64::pyjwt-1.7.1-py37_0
    defaults/win-64::pyopenssl-19.1.0-py37_0
    defaults/win-64::nbconvert-5.6.1-py37_0
    defaults/noarch::oauthlib-3.1.0-py_0
    defaults/noarch::prompt_toolkit-3.0.4-0
    defaults/win-64::urllib3-1.25.8-py37_0
    defaults/noarch::botocore-1.15.39-py_0
    defaults/win-64::ipython-7.13.0-py37h5ca1d4c_0
    defaults/win-64::requests-2.23.0-py37_0
    defaults/win-64::ipykernel-5.1.4-py37h39e3cac_0
    defaults/noarch::requests-oauthlib-1.3.0-py_0
    defaults/win-64::s3transfer-0.3.3-py37_0
    defaults/noarch::boto3-1.12.39-py_0
    defaults/noarch::google-auth-oauthlib-0.4.1-py_2
    defaults/noarch::jupyter_console-6.1.0-py_0
    defaults/win-64::notebook-6.0.3-py37_0
    defaults/noarch::qtconsole-4.7.2-py_0
    defaults/win-64::widgetsnbextension-3.5.1-py37_0
    defaults/noarch::ipywidgets-7.5.1-py_0
    defaults/win-64::jupyter-1.0.0-py37_7
    defaults/noarch::opt_einsum-3.1.0-py_0
    defaults/noarch::pandas-datareader-0.8.1-py_0
    defaults/noarch::tensorboard-2.1.0-py3_0
    defaults/noarch::tensorflow-estimator-2.0.0-pyh2649769_0
    defaults/win-64::h5py-2.10.0-py37h5e291fa_0
    defaults/noarch::keras-applications-1.0.8-py_0
    defaults/win-64::matplotlib-3.1.3-py37_0
    defaults/win-64::matplotlib-base-3.1.3-py37h64f37c6_0
    defaults/win-64::mkl_fft-1.0.15-py37h14836fe_0
    defaults/win-64::mkl_random-1.1.0-py37h675688f_0
    defaults/win-64::numpy-1.18.1-py37h93ca92e_0
    defaults/win-64::pandas-1.0.3-py37h47e9c7a_0
    defaults/win-64::scipy-1.4.1-py37h9439919_0
    defaults/noarch::keras-preprocessing-1.1.0-py_1
    defaults/win-64::scikit-learn-0.22.1-py37h6288b17_0
    defaults/win-64::tensorflow-base-2.0.0-eigen_py37h01553b8_0
    defaults/win-64::tensorflow-2.0.0-eigen_py37hbfc5123_0

Preparing transaction: ...working... done
Verifying transaction: ...working... failed
Traceback (most recent call last):
  File "C:\Users\admin\miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "C:\Users\admin\miniconda3\lib\site-packages\conda_env\cli\main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\admin\miniconda3\lib\site-packages\conda_env\cli\main_create.py", line 111, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "C:\Users\admin\miniconda3\lib\site-packages\conda_env\installers\conda.py", line 40, in install
    unlink_link_transaction.execute()
  File "C:\Users\admin\miniconda3\lib\site-packages\conda\core\link.py", line 244, in execute
    self.verify()
  File "C:\Users\admin\miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Users\admin\miniconda3\lib\site-packages\conda\core\link.py", line 234, in verify
    maybe_raise(CondaMultiError(exceptions), context)
  File "C:\Users\admin\miniconda3\lib\site-packages\conda\exceptions.py", line 1019, in maybe_raise
    raise error
conda.CondaMultiError: The package for hdf5 located at C:\Users\admin\miniconda3\pkgs\hdf5-1.10.4-h7ebc959_0
appears to be corrupted. The path 'Library/bin/h5unjam.exe'
specified in the package manifest cannot be found.

The package for qt located at C:\Users\admin\miniconda3\pkgs\qt-5.9.7-vc14h73c81de_0
appears to be corrupted. The path 'Library/bin/assistant.exe'
specified in the package manifest cannot be found.

The package for qt located at C:\Users\admin\miniconda3\pkgs\qt-5.9.7-vc14h73c81de_0
appears to be corrupted. The path 'Library/bin/designer.exe'
specified in the package manifest cannot be found.

The package for qt located at C:\Users\admin\miniconda3\pkgs\qt-5.9.7-vc14h73c81de_0
appears to be corrupted. The path 'Library/bin/qmlcachegen.exe'
specified in the package manifest cannot be found.

The package for qt located at C:\Users\admin\miniconda3\pkgs\qt-5.9.7-vc14h73c81de_0
appears to be corrupted. The path 'Library/bin/qmlplugindump.exe'
specified in the package manifest cannot be found.

****This transaction has incompatible packages due to a shared path.
  packages: defaults/win-64::notebook-6.0.3-py37_0, defaults/win-64::notebook-6.0.3-py37_0
  path: 'menu/notebook.json'****
![Screenshot (52)](https://user-images.githubusercontent.com/53796244/79661028-cfa3fc00-81d1-11ea-8c69-672c734d04fa.png)
`

**Comment by jeffheaton** [comment]
Suggest asking this on TensorFlow's GitHub.  I've not seen this issue before.  https://github.com/tensorflow/tensorflow
