### ISSUE TITLE
I followed your tutorial but i have an error

### ISSUE THREAD

**Issue by mabozaid2003** [jeffheaton/t81_558_deep_learning#60]
OSError: SavedModel file does not exist at: ../dnn/mpg_model.h5/{saved_model.pbtxt|saved_model.pb}
why this error when I run python mpg_server_1.py 
how can I solve this ?

**Comment by jeffheaton** [comment]
Where are you getting this error at?

**Comment by mabozaid2003** [comment]
I solved it Thanks when I run python file I got this error so I install Tensorflow gpu and Flask in my python 3.6

**Comment by mabozaid2003** [comment]
Thanks I solved this. Sorry for the late reply

‫في السبت، 16 مايو 2020 في 5:05 م تمت كتابة ما يلي بواسطة ‪Jeff Heaton‬‏ <‪
notifications@github.com‬‏>:‬
