### ISSUE TITLE
Miniconda env MacOS issue

### ISSUE THREAD

**Issue by vinamramunot-tech** [jeffheaton/t81_558_deep_learning#65]
# Error
<img width="965" alt="Screen Shot 2020-06-03 at 12 56 06 AM" src="https://user-images.githubusercontent.com/56406734/83561221-19a03180-a535-11ea-8192-ca58ebd366c4.png">

# Files tree
I have a directory by the name of **Miniconda3** in the user directory. I have uploaded an image below:

<img width="435" alt="Screen Shot 2020-06-03 at 1 00 29 AM" src="https://user-images.githubusercontent.com/56406734/83561558-aba83a00-a535-11ea-83b3-ff54d53e849e.png">

# MacOS version
macOS Catalina 10.15.5

**Comment by jeffheaton** [comment]
You are getting an error one-by-one of the components of the tensorflow.yml.  Suggest running each line one-by-one to see which is giving you an issue.  Let me know which package is not installing.

**Comment by vinamramunot-tech** [comment]
I have two questions, I accidentally downloaded the Miniconda two ways. One through the pkg file and the other one using a .sh script for macOS 64. Now one instance is in /opt/miniconda3 and the other one is /Users/"my name"/miniconda3. The /opt/ was the one downloaded the first time using pkg installer and the /Users/"my name"/  was downloaded using the .sh script. Is it advisable to delete one of the instance?

**Comment by vinamramunot-tech** [comment]
> You are getting an error one-by-one of the components of the tensorflow.yml. Suggest running each line one-by-one to see which is giving you an issue. Let me know which package is not installing.

To run the individually, do I need to use this command every time:
```bash
conda env create python=3.7
conda env create pip&gt;=19.0
```

**Comment by vinamramunot-tech** [comment]
> You are getting an error one-by-one of the components of the tensorflow.yml. Suggest running each line one-by-one to see which is giving you an issue. Let me know which package is not installing.

One of the errors I have figured out that when I am downloading the tensor flow.yml file, it adds somethings to the heading and the footer of the file, so I removed it and now it is giving me a better error. I mean less error than before. 

# New error

<img width="1238" alt="Screen Shot 2020-06-03 at 12 33 37 PM" src="https://user-images.githubusercontent.com/56406734/83606189-ceb70600-a596-11ea-9a6d-6d10e5a81df0.png">


### error explained
error is talking about specifying the version of pip as a explicit dependency. 

#### Could this be a solution
should I place the pip"3" outside in the yml file. I have uploaded an image of the yml file. 

<img width="357" alt="Screen Shot 2020-06-03 at 12 42 48 PM" src="https://user-images.githubusercontent.com/56406734/83606768-c1e6e200-a597-11ea-9d84-be171e057f85.png">
