### ISSUE TITLE
Error running in Colab

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [jeffheaton/t81_558_deep_learning#69]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-6d62b114295b> in <module>()
     10 import numpy as np
     11 
---> 12 import tensorflow as tf
     13 
     14 from tf_agents.agents.ddpg import actor_network

3 frames
/usr/local/lib/python3.6/dist-packages/google/protobuf/any_pb2.py in <module>()
     19   syntax='proto3',
     20   serialized_options=b'\n\023com.google.protobufB\010AnyProtoP\001Z%github.com/golang/protobuf/ptypes/any\242\002\003GPB\252\002\036Google.Protobuf.WellKnownTypes',
---> 21   create_key=_descriptor._internal_create_key,
     22   serialized_pb=b'\n\x19google/protobuf/any.proto\x12\x0fgoogle.protobuf\"&\n\x03\x41ny\x12\x10\n\x08type_url\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x42o\n\x13\x63om.google.protobufB\x08\x41nyProtoP\x01Z%github.com/golang/protobuf/ptypes/any\xa2\x02\x03GPB\xaa\x02\x1eGoogle.Protobuf.WellKnownTypesb\x06proto3'
     23 )

AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by jeffheaton** [comment]
There are instructions in the notebook that cover that:

```
Note, if you get the following error, restart and rerun the Google CoLab environment. Sometimes a restart is needed after installing TF-Agents.

AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```
