### ISSUE TITLE
i am facing error while installing gym

### ISSUE THREAD

**Issue by ashubansal005** [jeffheaton/t81_558_deep_learning#70]
using 
pip install --exists-action i --upgrade gym

error have 
ERROR: spyder 4.1.3 requires pyqt5<5.13; python_version >= "3", which is not installed.
ERROR: spyder 4.1.3 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.

**Comment by ashubansal005** [comment]
also face error in tensorflow while typing
import tensorflow as tf


ImportError: DLL load failed: The specified module could not be found.
Failed to load the native TensorFlow runtime.

**Comment by jeffheaton** [comment]
Usually that error comes from not doing **conda activate tensorflow** before **jupyter notebook**.  I've not seen the error above.  I suggest filing an issue with gym to see if they have any suggestions.  Since it is their library, they can support you better than me.
