### ISSUE TITLE
Not clear what you mean by "dummy variables" in assignment two.

### ISSUE THREAD

**Issue by crimsonalucard** [jeffheaton/t81_558_deep_learning#72]
You mention that the final dataframe should have a bunch of columns but what data is located in these columns? Can you be more clear?

**Comment by jeffheaton** [comment]
Dummy variables are explained here:  https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_02_2_pandas_cat.ipynb

Basically, if you have a column that is textual, and may hold any of the distinct values "a", "b", "c", you expand it to 3 columns and encode as follows

a = 0,0,1
b = 0,1,0
c = 1,0,0
