### ISSUE TITLE
Not able to install tensorflow 2.2.0 

### ISSUE THREAD

**Issue by Atharv17** [jeffheaton/t81_558_deep_learning#76]
I changed the version of tensorflow in yml file , and tried to install , But its not working , 
![issue](https://user-images.githubusercontent.com/42394863/92072807-b641cc00-edcf-11ea-88a6-60ada936b0d8.JPG)

**Comment by jeffheaton** [comment]
Not sure CONDA has released 2.2 yet; they had not at the time that I wrote these instructions.

**Comment by Atharv17** [comment]
okay , actually i am trying to do transfer learning of Unets using segmentation models so for that it required tensorflow 2.2.0 or  higher version

**Comment by jeffheaton** [comment]
Yes I just checked, Anaconda forge is at 2.1 for Windows.  I do wish they would not get so far behind, CoLab is at 2.3 already.  You would need to install the drivers system level and install right from PIP, would be the best option to get 2.2 or 2.3.  But the templates I have here for the class won't work for that until 2.2 is released in anaconda forge.
