### ISSUE TITLE
### Multi class error

### ISSUE THREAD

**Issue by pavannaikmu** [jeffheaton/t81_558_deep_learning#77]
Sir, 
I'm working on the code of iris classification and i get an error in the last three cells of the classification, please help me out with it. i have updated the version of the sklearn but still same error
![version](https://user-images.githubusercontent.com/62498125/92319033-63cffd80-efd1-11ea-852a-005f28e05afd.png)

![roc_error](https://user-images.githubusercontent.com/62498125/92319031-603c7680-efd1-11ea-8659-5248f00fcb0b.png)

###code link
https://github.com/OmarMedhat22/Iris-Recognition-CASIA-Iris-Thousand/blob/master/iris_classification_2.ipynb

**Comment by jeffheaton** [comment]
I will take a look.
