### ISSUE TITLE
[correction] t81_558_class_03_2_keras.ipynb

### ISSUE THREAD

**Issue by gpk2000** [jeffheaton/t81_558_deep_learning#79]
In this code below you forgot to add `f` at the beginning of the second string
![image](https://user-images.githubusercontent.com/56096830/93428817-c08abc80-f8dd-11ea-9146-763e798171b8.png)

It should be
```py
# Sample predictions
for i in range(10):
    print(f"{i+1}. Car name: {cars[i]}, MPG: {y[i]}, " 
          + f"predicted MPG: {pred[i]}")
``` 

Notice the `f` before predicted.

**Comment by jeffheaton** [comment]
You are right!  Thanks.
