### ISSUE TITLE
T81-558: Applications of Deep Neural Networks Module 13: Advanced/Other Topics

### ISSUE THREAD

**Issue by strategiepilot** [jeffheaton/t81_558_deep_learning#82]
Hi Jeff, first of all, thanks a ton for your wonderful course, the hands-on coding and giving people the opportunity to access them for free online!

I've been trying to follow along your tutorial in module 18 to deploy a pretrained model with AWS Sagemaker.
In chapter 13.2 Step 2: Load the Keras model using the JSON and weights file i am running into the followin value error: 

_ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you._

I tried to wrap it into a tf.Variable(lambda ...) but that gets me some new errors.
Not sure, how to resolve this but really would like to be able to process further in this tutorial.
thx for looking into this.
Andreas from Germany

**Comment by jeffheaton** [comment]
I will have to try to run through this example again.  AWS may have changed something since when I first created it.

**Comment by jeffheaton** [comment]
I am replacing this material with other topics for the course.
