### ISSUE TITLE
"AttributeError: module 'dnnlib' has no attribute 'SubmitConfig" 

### ISSUE THREAD

**Issue by eluzzi5** [jeffheaton/t81_558_deep_learning#87]
I am running into the error "AttributeError: module 'dnnlib' has no attribute 'SubmitConfig" after running the code: sc = dnnlib.SubmitConfig()

Since this is coming from the dnnlib, which was not written by me, I'm not sure how to proceed. Any help would be greatly appreciated! :)

**Comment by EricHallahan** [comment]
Digging into this, this looks like an oversight after the recent port from `NVlabs/stylegan2` to `NVlabs/stylegan2-ada`. (47bbf0a and 0d7490f). `t81_558_class_07_3_style_gan.ipynb` should be rewritten to not use `dnnlib.SubmitConfig` and the currently undefined `pretrained_networks` object in **Examining the Latent Vector**.

**Comment by eluzzi5** [comment]
> Digging into this, this looks like an oversight after the recent port from `NVlabs/stylegan2` to `NVlabs/stylegan2-ada`. ([47bbf0a](https://github.com/jeffheaton/t81_558_deep_learning/commit/47bbf0af4f7003324dc138cbd43717ba4c23ee06) and [0d7490f](https://github.com/jeffheaton/t81_558_deep_learning/commit/0d7490f750fff8203a715163c98b835c2d5da60e)). `t81_558_class_07_3_style_gan.ipynb` should be rewritten to not use `dnnlib.SubmitConfig` and the currently undefined `pretrained_networks` object in **Examining the Latent Vector**.

thank you so much!
