### ISSUE TITLE
showing len(img)=0, could you please resolve it 

### ISSUE THREAD

**Issue by ramidim** [jeffheaton/t81_558_deep_learning#91]
len(img)

0

**Comment by jeffheaton** [comment]
Which notebook are you reporting an issue with?

**Comment by ramidim** [comment]
I am using google collab

**Comment by jeffheaton** [comment]
I have no idea what you are asking me.

**Comment by ramidim** [comment]
For code 
Len(img)

I am getting output '0'

I think is not showing the count of images.

**Comment by jeffheaton** [comment]
Do you have any images in the list?  Where are you getting this?  Are you reporting an issue with one of the notebooks.  I have no context here.

**Comment by ramidim** [comment]
yes I have flicker8K dataset
![Capture](https://user-images.githubusercontent.com/77604245/105624835-b6a83580-5e4a-11eb-8c7b-f3755966459b.PNG)

**Comment by jeffheaton** [comment]
When I run that example I do not get the issue.  Unfortunately, I do not have a great deal of time to help with issues one-to-one.  Probably a good question for StackOverflow or similar.
