### ISSUE TITLE
Run StyleGAN2 From Python Code

### ISSUE THREAD

**Issue by perryjamessugden** [jeffheaton/t81_558_deep_learning#93]
Hey 

I've run into a recent issue of when running the follow line (in colab)
I can still run this line, no issues with some older generated .pkl files.

**Run StyleGAN2 From Python Code**

import IPython.display

URL = "......" 
tflib.init_tf()
print('Loading networks from "%s"...' % URL)
with dnnlib.util.open_url(URL) as fp:
    _G, _D, Gs = pickle.load(fp)
    
    --------------------------------------------------------------
    Loading networks from "...."...
Downloading  ... done
---------------------------------------------------------------------------
**UnpicklingError                           Traceback (most recent call last)
<ipython-input-13-c0f853c7dca1> in <module>()
      6 print('Loading networks from "%s"...' % URL)
      7 with dnnlib.util.open_url(URL) as fp:
----> 8     _G, _D, Gs = pickle.load(fp)

UnpicklingError: invalid load key, '\x0a'.**

**Comment by jeffheaton** [comment]
I will take a look

**Comment by perryjamessugden** [comment]
Thanks so much

**Comment by perryjamessugden** [comment]
I was able to resolve, following this
https://github.com/xinntao/ESRGAN/issues/67

**Comment by jeffheaton** [comment]
I think this resolves this too, https://github.com/jeffheaton/t81_558_deep_learning/blob/daab5359c582677afd50a8688326858bb41181e6/t81_558_class_07_3_style_gan.ipynb
