### ISSUE TITLE
Is there any way to save the model as .pkl file?

### ISSUE THREAD

**Issue by kirkegross** [jeffheaton/t81_558_deep_learning#94]
Hi!

Thank you for this code. I'm new to all this. So might be a stupid question, but is it possible to save the model as .pkl instead of .h5 file? Or is there any way to convert it to .pkl file after saving it as .h5 file?

Best,
Kirke

**Comment by jeffheaton** [comment]
I usually save to H5, but more info on pickle here:  https://medium.com/@maxwellflitton/pickling-keras-models-c10f7c1b99b1
