### ISSUE TITLE
IDS with DRL

### ISSUE THREAD

**Issue by FatenLoua** [jeffheaton/t81_558_deep_learning#96]
Dear Mr. Jeff,
I want to build an IDS based on Deep reinforcement learning, Can you help me with a basic code that  can start with ( environment, states, actions). 
 I have found a few projects in this area but your code is still simple and easy to understand that's why I prefer it. Thank you for your response.

**Comment by jeffheaton** [comment]
I am closing just because this is not an issue with any of the code in the class.  I will keep this in mind for a future project, though, but do not have a great deal of time to help on individual projects.

**Comment by FatenLoua** [comment]
ok.
Thank you for your response.
