### ISSUE TITLE
TypeError: Environment should implement py_environment.PyEnvironment

### ISSUE THREAD

**Issue by ToutaF** [jeffheaton/t81_558_deep_learning#98]
Hi Mr Jeff,
I'm tring to execute the code which create own environment in my own pc but I get this error:
TypeError: Environment should implement py_environment.PyEnvironment
  In call to configurable 'TFPyEnvironment' (<class 'tf_agents.environments.tf_py_environment.TFPyEnvironment'>)
How can I fix this issue. Thank you

**Comment by jeffheaton** [comment]
Which of my source files are you trying to execute? How do I reproduce this error?

**Comment by ToutaF** [comment]
Moduld 12 part 12.5

**Comment by jeffheaton** [comment]
https://github.com/jeffheaton/t81_558_deep_learning/blob/master/t81_558_class_12_05_apply_rl.ipynb

**Comment by jeffheaton** [comment]
I tried running this in colab, and did not get any errors.  If this is still an issue, let me know exactly which line you see this on.  Likely an old version of one of the libraries I guess.
