### ISSUE TITLE
 AttributeError: module 'dnnlib' has no attribute 'SubmitConfig'

### ISSUE THREAD

**Issue by nfcodetm** [jeffheaton/t81_558_deep_learning#99]
sir getting error 
 i am using your colab notebook code sir

**Comment by jeffheaton** [comment]
Should be resolved now:  https://github.com/jeffheaton/t81_558_deep_learning/blob/daab5359c582677afd50a8688326858bb41181e6/t81_558_class_07_3_style_gan.ipynb
